import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import { FormProvider } from "@/context/Formcontext";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const ubuntu = Ubuntu({
    variable: "--font-ubuntu",
    subsets: ["latin"],
    display: "swap",
    weight: ["300", "400", "500", "700"],
    style: ["normal", "italic"],
    fallback: ["system-ui", "sans-serif"],
    preload: true,
    adjustFontFallback: true,
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${ubuntu.variable} antialiased grid place-items-center`}
            >
                <FormProvider>{children}</FormProvider>
            </body>
        </html>
    );
}
